import type { SportType } from "../types";

const sportTypeLabels: Record<SportType | "", string> = {
  "": "Other",
  AlpineSki: "Alpine Ski",
  BackcountrySki: "Backcountry Ski",
  Badminton: "Badminton",
  Canoeing: "Canoeing",
  Crossfit: "Crossfit",
  EBikeRide: "E-Bike Ride",
  Elliptical: "Elliptical",
  EMountainBikeRide: "E-Mountain Bike Ride",
  Golf: "Golf",
  GravelRide: "Gravel Ride",
  Handcycle: "Handcycle",
  HighIntensityIntervalTraining: "HIIT",
  Hike: "Hike",
  IceSkate: "Ice Skate",
  InlineSkate: "Inline Skate",
  Kayaking: "Kayaking",
  Kitesurf: "Kitesurf",
  MountainBikeRide: "Mountain Bike Ride",
  NordicSki: "Nordic Ski",
  Pickleball: "Pickleball",
  Pilates: "Pilates",
  Racquetball: "Racquetball",
  Ride: "Ride",
  RockClimbing: "Rock Climbing",
  RollerSki: "Roller Ski",
  Rowing: "Rowing",
  Run: "Run",
  Sail: "Sail",
  Skateboard: "Skateboard",
  Snowboard: "Snowboard",
  Snowshoe: "Snowshoe",
  Soccer: "Soccer",
  Squash: "Squash",
  StairStepper: "Stair Stepper",
  StandUpPaddling: "Stand Up Paddling",
  Surfing: "Surfing",
  Swim: "Swim",
  TableTennis: "Table Tennis",
  Tennis: "Tennis",
  TrailRun: "Trail Run",
  Velomobile: "Velomobile",
  VirtualRide: "Virtual Ride",
  VirtualRow: "Virtual Row",
  VirtualRun: "Virtual Run",
  Walk: "Walk",
  WeightTraining: "Weight Training",
  Wheelchair: "Wheelchair",
  Windsurf: "Windsurf",
  Workout: "Workout",
  Yoga: "Yoga",
};

export function getActivityLabel(sportType?: SportType): string {
  return sportTypeLabels[sportType ?? ""] ?? sportTypeLabels[""];
}