import {
  DirectionsRun as RunIcon,
  DirectionsBike as BikeIcon,
  DirectionsWalk as WalkIcon,
  Hiking as HikingIcon,
  DownhillSkiing as DownhillSkiingIcon,
  NordicWalking as NordicWalkingIcon,
  Snowboarding as SnowboardingIcon,
  Kayaking as KayakingIcon,
  Pool as PoolIcon,
  Rowing as RowingIcon,
  Surfing as SurfingIcon,
  SportsGolf as SportsGolfIcon,
  FitnessCenter as FitnessCenterIcon,
  SelfImprovement as SelfImprovementIcon,
  SportsSoccer as SportsSoccerIcon,
  Sports as SportsIcon,
  SportsTennis as SportsTennisIcon,
} from "@mui/icons-material";
import type { ReactNode } from "react";
import type { SportType } from "../types";

const sportTypeIcons: Record<SportType | "", ReactNode> = {
  "": <SportsIcon fontSize="inherit" color="primary" />,
  AlpineSki: <DownhillSkiingIcon fontSize="inherit" color="primary" />,
  BackcountrySki: <DownhillSkiingIcon fontSize="inherit" color="primary" />,
  Badminton: <SportsTennisIcon fontSize="inherit" color="primary" />,
  Canoeing: <KayakingIcon fontSize="inherit" color="primary" />,
  Crossfit: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  EBikeRide: <BikeIcon fontSize="inherit" color="primary" />,
  Elliptical: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  EMountainBikeRide: <BikeIcon fontSize="inherit" color="primary" />,
  Golf: <SportsGolfIcon fontSize="inherit" color="primary" />,
  GravelRide: <BikeIcon fontSize="inherit" color="primary" />,
  Handcycle: <BikeIcon fontSize="inherit" color="primary" />,
  HighIntensityIntervalTraining: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  Hike: <HikingIcon fontSize="inherit" color="primary" />,
  IceSkate: <NordicWalkingIcon fontSize="inherit" color="primary" />,
  InlineSkate: <NordicWalkingIcon fontSize="inherit" color="primary" />,
  Kayaking: <KayakingIcon fontSize="inherit" color="primary" />,
  Kitesurf: <SurfingIcon fontSize="inherit" color="primary" />,
  MountainBikeRide: <BikeIcon fontSize="inherit" color="primary" />,
  NordicSki: <NordicWalkingIcon fontSize="inherit" color="primary" />,
  Pickleball: <SportsTennisIcon fontSize="inherit" color="primary" />,
  Pilates: <SelfImprovementIcon fontSize="inherit" color="primary" />,
  Racquetball: <SportsTennisIcon fontSize="inherit" color="primary" />,
  Ride: <BikeIcon fontSize="inherit" color="primary" />,
  RockClimbing: <HikingIcon fontSize="inherit" color="primary" />,
  RollerSki: <NordicWalkingIcon fontSize="inherit" color="primary" />,
  Rowing: <RowingIcon fontSize="inherit" color="primary" />,
  Run: <RunIcon fontSize="inherit" color="primary" />,
  Sail: <SurfingIcon fontSize="inherit" color="primary" />,
  Skateboard: <SportsIcon fontSize="inherit" color="primary" />,
  Snowboard: <SnowboardingIcon fontSize="inherit" color="primary" />,
  Snowshoe: <HikingIcon fontSize="inherit" color="primary" />,
  Soccer: <SportsSoccerIcon fontSize="inherit" color="primary" />,
  Squash: <SportsTennisIcon fontSize="inherit" color="primary" />,
  StairStepper: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  StandUpPaddling: <RowingIcon fontSize="inherit" color="primary" />,
  Surfing: <SurfingIcon fontSize="inherit" color="primary" />,
  Swim: <PoolIcon fontSize="inherit" color="primary" />,
  TableTennis: <SportsTennisIcon fontSize="inherit" color="primary" />,
  Tennis: <SportsTennisIcon fontSize="inherit" color="primary" />,
  TrailRun: <RunIcon fontSize="inherit" color="primary" />,
  Velomobile: <BikeIcon fontSize="inherit" color="primary" />,
  VirtualRide: <BikeIcon fontSize="inherit" color="primary" />,
  VirtualRow: <RowingIcon fontSize="inherit" color="primary" />,
  VirtualRun: <RunIcon fontSize="inherit" color="primary" />,
  Walk: <WalkIcon fontSize="inherit" color="primary" />,
  WeightTraining: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  Wheelchair: <SportsIcon fontSize="inherit" color="primary" />,
  Windsurf: <SurfingIcon fontSize="inherit" color="primary" />,
  Workout: <FitnessCenterIcon fontSize="inherit" color="primary" />,
  Yoga: <SelfImprovementIcon fontSize="inherit" color="primary" />,
};

export function getActivityIcon(sportType?: SportType): React.ReactElement {
  return (sportTypeIcons[sportType ?? ""] ?? sportTypeIcons[""]) as React.ReactElement;
}